### ISSUE TITLE
Defining scope

### ISSUE THREAD

**Issue by ccarbonellg** [ccarbu/py_html5_output#2]
Hi @ccarbu,

Please, define a short scope.

Thanks,

**Comment by ccarbu** [comment]
Hi @ccarbonellg,

I will do my best in #1.

Regards,

**Comment by ccarbu** [comment]
> Hi @ccarbu,
> 
> Please, define a short scope.
> 
> Thanks,

Hi @ccarbonellg,

I will do my best in https://github.com/ccarbu/py_html5_output/issues/1.

Regards,

**Comment by ccarbu** [comment]
> Hi @ccarbu,
> 
> Please, define a short scope.
> 
> Thanks,

Hi @ccarbonellg,

I will do my best in https://github.com/ccarbu/py_html5_output/issues/1.

Regards,

**Comment by ccarbu** [comment]
> Hi @ccarbu,
> 
> Please, define a short scope.
> 
> Thanks,

Hi @ccarbonellg,

I will do my best in https://github.com/ccarbu/py_html5_output/issues/1.

Regards,
